### ISSUE TITLE
README in Register is faulty

### ISSUE THREAD

**Issue by aseea** [aseea/1DV450_jn222iw_API#1]
Not good enough instructions to get application running locally. Needs better information about database and seeds.

**Comment by HenrikGabrielsson** [comment]
Hej!

Här kommer lite kritik på din applikation.

# Installation

Installationen var lite knepig. För det första saknas filen config/secrets.yml som man inte kan starta upp applikationen utan. Jag kopierade filen från mitt eget projekt och testade, och det fungerade, men kan ju vara bra och dela den på Github också ;)
Efter detta så körde jag *rake db:migrate* och *rake db:seed* för att plocka in datan från din seed-fil i databasen, och jag lade då också till administratören som inte fanns där.

# Felhantering
Bra att man får feedback när man gör saker i applikationen, och meddelanden var beskrivande och enkla att förstå. Du kanske också skulle behöva en felsida när man försöker komma åt en sida som inte finns (404). I nuläget får man bara standardsidan från Rails som inte är så rolig.

# Validering
All validering fungerar bra. Har inget att klaga på här.

# Säkerhet
Jag kunde inte hitta några säkerhetsfel. Tror att detta fungerar bra också.

# Kodkvalitet
Bra kvalitet på koden. Kanske skulle ha funnits lite mer kommentarer. I sessions_helper fanns det många funktioner som kanske inte alltid var helt nödvändiga.
Bra att du delat upp modellen i flera olika klasser (keys, users, admin). Detta gör i alla fall så att jag förstår applikationen enklare, och det känns logiskt.

# Gränssnitt/Funktionalitet
Bra, enkelt gränssnitt som fungerar och är lätt att förstå. Jag hade nog gärna kunnat ta bort enbart nyckeln (och låta användaren finnas kvar) men vet inte om detta är ett krav. 
Man kan logga in som flera användare samtidigt, vilket kanske verkar lite konstigt, men inte direkt någon säkerhetsrisk, så antar att det är OK också. Ett förslag är att det kanske ska finnas en utloggningsknapp på alla sidor (i layouts/application.html.erb?) så länge man är inloggad, så att man alltid kan logga ut.

Förutom en lite jobbig installation så tycker jag att du har gjort en bra applikation!

MVH Henrik Gabrielsson, hg222aa

**Comment by aseea** [comment]
Tack för bra och konkret kritik! Insåg själv att instruktionerna inte var kompletta och ska åtgärda detta snart. Angående att ta bort både användaren & nyckeln samtidigt så tänkte jag såhär: en nyckel per e-mail. Det man skulle kunna ha gjort är att antingen låta användaren skapa en ny nyckel efter borttagning av nyckel, eller att allt togs bort samtidigt då det är onödigt att ha en användare utan nyckel. Däremot så hade jag velat veta hur du tycker att man ska sköta admin funktionerna. Så som det är nu så blir inte användaren meddelad om dess nyckel/användare blir borttagen. Funderade på att ha en tabell som lagrar borttagna eposter som då får ett meddelande när de försöker logga in. Vad tror du om det?

**Comment by HenrikGabrielsson** [comment]
Jag förstår att det kan kännas dumt att ta bort nyckeln men inte användaren (eftersom användaren blir helt värdelös utan en nyckel). Jag skulle däremot förslå att du enbart tar bort nyckeln, eftersom du då kan fortsätta spara email-adressen. Då slipper du lägga till en extra tabell i databasen, och du kan ändå meddela användare som loggar in om att deras nyckel har blivit borttagen. Eftersom du (smart nog) sparar nyckeln i en egen modellklass, så blir det inga tomma fält i databasen heller.

**Comment by aseea** [comment]
Låter logiskt och bra! En till fråga: tycker du att användaren ska kunna skapa en ny nyckel då? Förmodligen så har nyckeln tagits bort för att den har missbrukats, då vill man väl inte att användaren kan skapa en ny?

**Comment by HenrikGabrielsson** [comment]
Det är upp till dig, men jag tycker som du att användaren inte ska kunna skapa en ny nyckel. Det har varit väldigt blandat hur folk har tolkat instruktionerna :)

**Comment by aseea** [comment]
Yes! Tack så mycket för att jag fick låna dig som bollplank :)

**Comment by HenrikGabrielsson** [comment]
Inga problem. kan alltid vara bra att diskutera vissa saker :)

**Comment by 1dv450** [comment]
Bra diskussioner och idé! Kul!
Vad det gäller saknad av config/secrets.yml så blir ju den borttagen av en korekt .gitignore och man brukar inte skicka upp den på github. Nu är det kanske ingen fara för det nu för tiden finns bara säkerhetshashar för development och production
