### ISSUE TITLE
Sammanfattning

### ISSUE THREAD

**Issue by mf222nb** [aseea/1DV450_jn222iw_API#15]
Koden ser bra ut och API:t i sig är väl gjord. Routesen ser bra ut och du använder dig bara av de routes du behöver och inte har några överflödiga routes vilket är bra. När man gör dina gets så får man ut väldigt mycket information om det man gör en get på vilket är väldigt trevligt och man ser vad som hänger ihop med vad. 

Lite mer kommentarer på koden hade uppskattats, särskilt på de delar som inte är så självklara vilket är JWT - token koden. I din POSTMAN - fil har du en POST som heter POST - Auth och en som heter POST - Atuh Successful vilket gjorde mig väldigt förvirrad och då blev det en onödig issue så den kanske skulle heta något annat för att undvika missförstånd. 

Allt som allt så är det ett bra API och du har gjort allt man behöver göra för ett godkänt API.

**Comment by aseea** [comment]
Tack för din input & ska definitivt lägga till kommentarer i koden för att göra den läsbar. Dock uppdaterar jag nog inte postman filen då den främst var till för dig :)
